# Generated by Django 4.1.7 on 2023-03-31 01:42

from django.db import migrations


def populate_status(apps, schemaeditor):
    status = {
        "To do",
        "In progress",
        "Done"
    }
    Status = apps.get_model("Issues", "Status")
    for key, desc in status.items():
        status_obj = Status(name=key, description=desc)
        status_obj.save()


def populate_priority(apps, schemaeditor):
    priority = {
        "Low", 
        "Medium", 
        "High"
    }
    Priority = apps.get_model("Issues", "Status")
    for key, desc in priority.items():
        priority_obj = Priority(name=key, description=desc)
        priority_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority)
    ]


